tsl0922/ttyd

- Dockerfile
Signed-off-by: Damien DUPORTAL <damien.duportal@gmail.com>
Hello !
This Pull Request is about the ttyd docker image. My goal was to shrink up the image size, given I was needed to free some space on my context.
On my Docker4Mac 1.13.0, the virtual image size reported by docker went from 482 Mb to 208 Mb:
```
$ docker build -t ttyd:latest ./
(... build log ...)
$ docker images | grep tty
ttyd            latest    20a69e0c3878    29 minutes ago    208 MB
tsl0922/ttyd    latest    f6566ed4599b    6 days ago        482 MB
```
Here are the PR actions:
- Replacing `MAINTAINER` by `LABEL` (since it is deprecated with Docker 1.13)
- Removing the `*-dev` and all building libs at the end (we don't need cmake when running ttyd for example) 
- Enforcing the ending cleaning by auto purging the …
> Shrinking image size

- Dockerfile-alpine
Signed-off-by: Damien DUPORTAL <damien.duportal@gmail.com>
This Pull Request introduce an alternative docker build based on Linux Alpine.
- A special GlibC build was needed
- LibWebSockets had to be built from source
The resulting image is ~68 Mb (~ 28 Mb when compressed from a docker registry).
You can find a pre-built version here: https://hub.docker.com/r/dduportal/ttyd/ to test
> Introduce Alpine Docker build

- Dockerfile-alpine
Fixes #46.
Tested with `alpine:edge`, the size of the built image is 7.76 MB only!
```
~ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ttyd                alpine              e1bb04471fa8        5 minutes ago       7.76 MB
alpine              edge                8914de95a28d        2 weeks ago         4 MB
alpine              latest              4a415e366388        2 weeks ago         3.99 MB
```
> Simplify docker alpine image building

- debian/changelog
Please try to bump the version in `debian/changelog` as well next time when the new upstream version bumps. Thanks
> Bump debian pkg version

- src/protocol.c
After forking, the websocket file descriptor is cloned and stored with the process.  After exec'ing the new function, there is no way to close the cloned file descriptor, which means that it won't be cleaned up until the whole process tree is cleaned up.
As long as it stays open, the original socket is blocked, which prevents us from restarting ttyd and reattaching to the original socket.
This change closes the socket so that it isn't leaked into child processes, meaning we can safely detach child processes and reconnect across sessions.
> Close websocket after forking to keep child processes from blocking new connections

- src/server.c
I've experienced `Ran out of header data space` while I have multiple sessions stored in my development server. (The different http servers runs on 3000,5000 and 8080 and stored cookie as a single domain) .
From [an issue](https://github.com/warmcat/libwebsockets/issues/1270),  libwebsocket has options to increase this.  For now,  just increase 5 times bigger than default(4096), which is sufficient for the most of the case, I believe.
Cookie section of request header is fat and it seems no way to control header from websocket JS api.
> Update max_heaser_data from default(4K) to 20K

- README.md
I wrote a live-ebuild for Gentoo users to facilitate installation of ttyd.  It's a work in progress and I hope to add the ability to install releases and not only from HEAD.  I am an official Gentoo Developer, but I want to work this separate from our infrastructure to ensure the quality before committing to the main tree.
> Add instructions for Gentoo Linux users

- src/server.h
Needed to unbreak build on OpenBSD.
> include pthread.h for pthread_mutex_t

- src/utils.c
Use errno.h rather than sysno/errno.h in utils.c, unbreaking build on OpenBSD (the "errno" symbol is only defined in errno.h not in sys/errno.h).
protocol.c and server.c already include errno.h rather than sys/errno.h so this should be safe on other OS here also.
> use errno.h not sys/errno.h in utils.c as in other files

- CMakeLists.txt
- src/http.c
According to warmcat/libwebsockets#537 and following my own experience, in some circumstances lws_get_peer_addresses can take several seconds to execute a reverse DNS request on a connected peer IP. The effect is that sometimes a websocket connection takes several seconds before it is established.
This PR addresses the described issue by replacing lws_get_peer_addresses with lws_get_peer_simple that completely skips the RDNS request.
Signed-off-by: Xiang Dai <764524258@qq.com>
> Avoid slow reverse-DNS requests caused by libwebsocket

- src/utils.c
On Android <signal.h> defines sys_signame, so trying to redefine it causes the build to fail.
This patch is used when building ttyd for [Termux](https://termux.com/).
> Avoid trying to redefine sys_signame on Android

- src/server.c
The strncpy function requires enough space for a NUL terminator.
> bugfix: off by one error

- src/http.c
Fixes compilation without deprecated OpenSSL APIs.
> http: add missing header

- README.md
- src/http.c
- src/protocol.c
- src/server.c
- src/server.h
The implementation is pretty straightforward, I replaced the hardcoded paths with an endpoint table, which by default has the hardcoded values, but can be prefixed with the value of the --base-path option.
Also, the following line (src/http.c:152) `if (strncmp(pss->path, "/token", 6) == 0) {` would match the url `/tokenwhatevercomesnext`, which I guess was not the intended goal. I changed to a regular strcmp which limits to the smallest string.
> Add -b, --base-path option for reverse proxies (#151)

- src/http.c
- src/server.c
- src/server.h
Common errors such as the one reported in #289 are eliminated with this PR. Additionally, the full endpoints are displayed to the user if the --base-path option is specified, making it easier to debug in case the user is providing incorrect input.
> Improvements for --base-path usage

- src/terminal.c
`pty` is a file descriptor (i.e. an int), not a pid.
> Fix type declaration

- src/protocol.c
Previously, if running in readonly mode (`-R`), we would keep
accumulating incoming websocket data to `pss->buffer`, resizing it with
every incoming message. This would also break the `RESIZE` operation as
we would never get rid of the `INPUT` message.
Now we discard `INPUT` messages in `readonly` mode, 1) allowing resize
to work and 2) preventing the buffer from growing indefinitely.
Tested by running `./ttyd -R tmux attach -r` and verifying that resize now works when it didn't before.
> fix readonly handling

- CMakeLists.txt
Specify that ttyd is a C project to avoid the
following build failure if a C++ compiler isn't found.
CMake Error at CMakeLists.txt:3 (project):
The CMAKE_CXX_COMPILER:
/home/bartekk/Projects/buildroots/buildroot-dev/buildroot/output/host/bin/arm-buildroot-linux-uclibcgnueabihf-g++
is not a full path to an existing compiler tool.
Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.
Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>
> cmake: fix build without C++

- src/http.c
len member is a size_t type so it can't be less than 0 by definition.
Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>
> src/http.c: fix checking pss's len member

- src/server.c
Our proxy disconnects tcp connection which has no transmission within 5 min. so I add a option to change websocket ping interval to keep connection.
How about this enhancement?
> add websocket ping interval option

- html/src/components/app.tsx
Enabling `set -g mouse on` in tmux.conf breaks copy-on-select.
On other keyboard layouts the shift key can be used as modifier for copy-on-select.
This commit enables the xterm options required for using the options key
as modifier for copy-on-select.
> xterm: enable macbook options key as modifier for copy-and-paste

- src/pty.c
When this was added in https://github.com/tsl0922/ttyd/commit/cfd338ea5e1a3c3023acade45980b3024c41e507
We before this time the *File descriptor flags* (`F_GETFD`/`F_SETFD`) were augmented to include `FD_CLOEXEC`
Then at this time the additional code added the *File status flags* (`F_GETFL`/`F_SETFL`) to include `O_NONBLOCK`, but this was weaved through code working with `F_SETFD` instead of `F_SETFL`. Some systems may use one big status word for all of them. Mine certainly dont.
FIXES #733
> pty.c: Fix errant use of fcntl F_SETFD

- src/protocol.c
Hi, after the 1.7.1 release we were still observing a rare segmentation fault in our ttyd-based application (about 10 crashes per day out of several hundred clients).
I was able to trace it back to a situation where a `RESIZE_TERMINAL` message is received, but the child process has already exited and the `pss->process` struct has been freed. In that case, the `cols` / `row` pointers into the struct still get dereferenced [here](https://github.com/tsl0922/ttyd/blob/45ef5784c168ff42b66fd6556f127c306c471027/src/protocol.c#L43-L44), causing a segmentation fault. I haven't able to replicate this crash in a local development environment, so I suspect network latency is required for this to happen.
With this patch, `RESIZE_TERMINAL` messages just get ignored if the process has been freed, …
> Avoid crash on resize message if process has exited

- src/pty.c
`async_cb ` frees `process` right after calling `uv_close`, which is prohibited. The correct method is using close callback.
See more information [here](https://github.com/tsl0922/ttyd/issues/994#issuecomment-1266215561)
> Fix use-after-free issue when closing a connection

- README.md
- snap/snapcraft.yaml
Hi, 
I've recently created a snap for ttyd and have it working with classic confinement. Meaning it will run "as native" within a snap container for any Linux distro supporting `snapd`. Learn more about snaps [here](https://snapcraft.io/about). 
I am happy to maintain the snap for your project, unless you'd prefer maintaining it all "in-house". There's not much anyone on the team would have to do, as the snaps are automatically built and published on the snap [store](https://snapcraft.io/store). 
As part of the security checks, pedigree, and validation, the upstream team/devs should at least know about it and agree with the publication as a `classic` snap. Basically, the snap will much like a `.deb` or `.rpm` on another distro supporting those packages; except it's distro agnostic. 
I …
> Snap created and ready for publication

- README.md
Changed **README.md** to include installation instructions with Scoop, a command line package manager for Windows.
> Added Scoop installation methods

- CMakeLists.txt
Fixes the following warning:
Compatibility with CMake < 2.8.12 will be removed from a future version of CMake.
> Bump CMake version to 2.8.12

- html/src/components/terminal/xterm/index.ts
According to [xterm.js](http://xtermjs.org/docs/guides/flowcontrol/#ideas-for-a-better-mechanism), pause and resume are in wrong places.
> fix flow control

- README.md
Also provides visibility of existing image, not mentioned in the readme.
> Add Docker pulls badge

- src/server.c
I would like to increase info.max_http_header_data to 65535 to resolve issues when you have to deal with large http headers.
> Increase info.max_http_header_data to max value of 65535

- html/package.json
- html/src/components/app.tsx
- html/src/components/terminal/xterm/addons/zmodem.ts
- html/src/components/terminal/xterm/index.ts
- html/yarn.lock
- src/server.c
> improve support for trzsz

- Dockerfile
- Dockerfile.alpine
Dockerfile best practices recommend to move the installation of external dependencies before specific code. This will improve local development experience by improving Docker cache management and it will improve final Docker images compaction by sharing the first layers.
> Leverage Docker Layer System

- README.md
- man/ttyd.1
- man/ttyd.man.md
- src/protocol.c
- src/server.c
- src/server.h
> server: add --exit-no-conn option
